### ISSUE TITLE
[Security issue]: Please take a look the security issue of the image 

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/containers#1]
we should fix these potential security issues. Please get advices from the right top corner "View recommend base image fixes"

<img width="1302" alt="Screenshot 2024-03-28 at 10 03 36 PM" src="https://github.com/SkywardAI/containers/assets/8053949/020d11d7-d1a6-43f4-b64c-62005ab07acb">

**Comment by arvin936** [comment]
I have also seen these reminders, mainly caused by python image and dependencies installed through pip. So to solve this problem, we need to communicate with Rob and solve it together.

**Comment by Aisuko** [comment]
As we discussed, many of these security issues do not have fixed version. And also, I bump the version of base image. So, if has fixed some critical security issues.


We close this one.
