### ISSUE TITLE
CI status icon issue

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/containers#21]
We change the CI process. The icon of CI status should be also changed.

Add icon below to the Readme.md

[![Building Checking 🚀](https://github.com/SkywardAI/containers/actions/workflows/build_check.yml/badge.svg)](https://github.com/SkywardAI/containers/actions/workflows/build_check.yml)

What you need to do are:
* fork repo
* add icon
* do PR

**Comment by duckling69** [comment]
Hey @Aisuko I'll like to work on it
